# This file was generated by GoReleaser. DO NOT EDIT.
cask "burnrate" do
  version "2.1.0"

  on_macos do
    on_intel do
      sha256 "5db22ec14f71b6c2abc79b64e3a6d17beb060b1094a7f64c8d6ffa85bfd4555d"
      url "https://getburnrate.io/releases/v#{version}/burnrate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5fb620e12c77d47a3ba144ecdc5c53acdf0e6d8686a051ae2f3223eebd5ae3f3"
      url "https://getburnrate.io/releases/v#{version}/burnrate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec7d91a79975be05b702cc6b1c8304b1e4d154cf07a3bd81554140d932ca6226"
      url "https://getburnrate.io/releases/v#{version}/burnrate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8bf515a4fab05ad1eeb6257f47770922504d0d1afe5c6c04a730739a70a5c719"
      url "https://getburnrate.io/releases/v#{version}/burnrate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "burnrate"
  desc "Local-first AI agent observability and cost analytics"
  homepage "https://getburnrate.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "burnrate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/burnrate"]
    end
  end

  # No zap stanza required

end
