# This file was generated by GoReleaser. DO NOT EDIT.
cask "burnrate" do
  version "2.0.2"

  on_macos do
    on_intel do
      sha256 "824e69bcb8619c178ee2aac420003b3c835b8dd31006c607cae339d5221dc54e"
      url "https://getburnrate.io/releases/v#{version}/burnrate_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f61c85401e62da6f7bb91f8b328712895a2f73d38cd24c3effbc6bef779ed3ff"
      url "https://getburnrate.io/releases/v#{version}/burnrate_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "63be6b3bb3ec04c674d9e5d468ccc11edf3c7c7992dd58d8c5152a54c89af68d"
      url "https://getburnrate.io/releases/v#{version}/burnrate_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8f550181ea868b3ed8bba250bc11fb4dd51dc094c61ccd68c3196452dc0f240b"
      url "https://getburnrate.io/releases/v#{version}/burnrate_#{version}_linux_arm64.tar.gz"
    end
  end

  name "burnrate"
  desc "Local-first AI agent observability and cost analytics"
  homepage "https://getburnrate.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "burnrate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/burnrate"]
    end
  end

  # No zap stanza required

end
