# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burnrate < Formula
  desc "AI usage analytics dashboard for Claude Code, Cursor, and Codex CLI"
  homepage "https://getburnrate.io"
  version "1.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/burnrate-dev/burnrate/releases/download/v1.0.1/burnrate_1.0.1_darwin_amd64.tar.gz"
    sha256 "9673d24fba8917f77b90bf97289c072541d6f92aa16e5cf1e6c18ef09747cf7d"

    define_method(:install) do
      bin.install "burnrate"
      (share/"burnrate").install Dir["static"]
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/burnrate-dev/burnrate/releases/download/v1.0.1/burnrate_1.0.1_darwin_arm64.tar.gz"
    sha256 "565b2f94507411062c4f18f845a216960cdf2495db587e64f18b4e85b9da939c"

    define_method(:install) do
      bin.install "burnrate"
      (share/"burnrate").install Dir["static"]
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/burnrate version")
  end
end
