# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burnrate < Formula
  desc "AI usage analytics dashboard for Claude Code, Cursor, and Codex CLI"
  homepage "https://getburnrate.io"
  version "1.2.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://getburnrate.io/releases/v1.2.0/burnrate_1.2.0_darwin_amd64.tar.gz"
    sha256 "49ba8602d723ea5dd3acb3b7cc72c0d99bdc85fa111a835d65795becde00e011"

    define_method(:install) do
      bin.install "burnrate"
      (share/"burnrate").install Dir["static"]
    end
  end
  if Hardware::CPU.arm?
    url "https://getburnrate.io/releases/v1.2.0/burnrate_1.2.0_darwin_arm64.tar.gz"
    sha256 "6d818e4370edc6baa36114c96866b7968b320c56764783765179a003819d3cb3"

    define_method(:install) do
      bin.install "burnrate"
      (share/"burnrate").install Dir["static"]
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/burnrate version")
  end
end
