# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Burnrate < Formula
  desc "AI usage analytics dashboard for Claude Code, Cursor, and Codex CLI"
  homepage "https://getburnrate.io"
  version "1.0.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/burnrate-dev/burnrate/releases/download/v1.0.0/burnrate_1.0.0_darwin_amd64.tar.gz"
    sha256 "3d343134cb33dddf63bf5cec579f9c9f97d6bdbfe1ba31e8214aa3c3f405588c"

    define_method(:install) do
      bin.install "burnrate"
      (share/"burnrate").install Dir["static"]
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/burnrate-dev/burnrate/releases/download/v1.0.0/burnrate_1.0.0_darwin_arm64.tar.gz"
    sha256 "ef88df71c15d357e21fa699d05a1a87fd19f744adbed9506ac0a4c02593a2845"

    define_method(:install) do
      bin.install "burnrate"
      (share/"burnrate").install Dir["static"]
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/burnrate version")
  end
end
